jsf:
    primefaces:
        theme: serenity-teal
        font-awesome: true

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        platform: postgres
        url: jdbc:postgresql://localhost:5432/docto
        username: postgres
        password: Pkg1522pam

    jpa:
        properties:
            hibernate:  
                dialect: org.hibernate.dialect.PostgreSQLDialect
                temp:
                    use_jdbc_metadata_defaults: falsespring.jpa.hibernate.ddl-auto=update
        database: POSTGRESQL
        show-sql: false

server:
    port:8080